version: "2"

services:

  bmg_backend:
    image: g0rd0nbl3u/bmg_backend:latest
    container_name: bmg_backend
    environment:
      - DB_HOST=mongodb:27017
      - DB_NAME=business_model_idea_generator
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - back-tier
      - www-tier
    restart: always

  bmg_frontend:
    image: g0rd0nbl3u/bmg_frontend:latest
    container_name: bmg_frontend
    ports:
      - "4200:80"
    networks:
      - back-tier
      - www-tier
    restart: always

  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    networks:
      - back-tier
    restart: always

volumes:
  mongodb-data:
    driver: local

networks:
  back-tier:
  www-tier:
